# Generated by Django 4.0.4 on 2022-10-02 03:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='nickname',
            field=models.CharField(help_text='Ten xe', max_length=30, validators=[django.core.validators.MinLengthValidator(3, 'hon ba ki tu')]),
        ),
        migrations.AlterField(
            model_name='make',
            name='name',
            field=models.CharField(help_text='Nhập hãng xe (Dodge, Honda...)', max_length=20, validators=[django.core.validators.MinLengthValidator(4, 'Phai co tu 4 ki tu!')]),
        ),
    ]
