# Generated by Django 4.0.4 on 2022-10-02 03:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0002_alter_auto_nickname_alter_make_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='make',
            name='name',
            field=models.CharField(help_text='Nhập hãng xe (Tesla, Dodge...)', max_length=20, validators=[django.core.validators.MinLengthValidator(4, 'Phai co tu 4 ki tu!')]),
        ),
    ]
