# Generated by Django 4.0.4 on 2022-09-30 19:27

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Make',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nhập hãng xe (Dodge, Honda...)', max_length=90, validators=[django.core.validators.MinLengthValidator(4, 'Phai co tu 4 ki tu!')])),
            ],
        ),
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(help_text='Ten xe', max_length=100, validators=[django.core.validators.MinLengthValidator(3, 'hon ba ki tu')])),
                ('mileage', models.PositiveIntegerField()),
                ('comment', models.CharField(max_length=200)),
                ('make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autos.make')),
            ],
        ),
    ]
